### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by nietsmmar** [OnurKaral/flutter_hcaptcha#1]
Is it possible to use this for `Flutter Web`?

**Comment by OnurKaral** [comment]
You can also use on Web

**Comment by nietsmmar** [comment]
Unfortunately that is not the case. As this package uses `https://pub.dev/packages/webview_flutter` which does not work in web.

**Comment by OnurKaral** [comment]
I will check & fix in free time

**Comment by nietsmmar** [comment]
Thank you. I appreciate this package a lot!
